refactor: implement responsive `TransactionTable`
ArkEcosystem/payvo-wallet pull request #1053
Opened 2022-02-23 12:36 UTC by goga-m

## Summary
Closes https://github.com/ArkEcosystem/payvo-wallet/issues/996

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-02-25 00:07 UTC, alfonsobries commented on src/utils/testing-library.tsx
> +		[key in LayoutBreakpoint | 'xs']: number;
In case you wonder why I am not adding `xs` to the `LayoutBreakpoint ` type is because I am introducing this type in #1055, #1056, and #1061 and is mostly used to match the Tailwindcss breakpoints (there is no `xs:something` in tailwind). Limiting only to tailwind breakpoints is probably going to be the most common use case for that type

2022-02-25 11:21 UTC, samharperpittam requested changes
@goga-m - I think we should remove/hide the 'Received / Sent' arrow which current resides next to the 'Sender'. Tis a bit confusing having the received icon next to the sender imo. The green or red `Amount` should be enough to determine if the transaction is sent or received. 

<img width="534" alt="image" src="https://user-images.githubusercontent.com/44671015/155706758-a5e511a1-11a6-4e9f-9fa3-aba1735bdebd.png">

2022-02-25 12:12 UTC, goga-m commented
@samharperpittam should be removed now :+1:

2022-02-25 13:19 UTC, samharperpittam approved these changes

2022-02-28 09:39 UTC, faustbrian approved these changes

2022-02-28 09:40 UTC, merged