refactor: responsive portfolio breakdown
ArkEcosystem/payvo-wallet pull request #1056
Opened 2022-02-23 19:03 UTC by alfonsobries

## Summary

Closes https://github.com/ArkEcosystem/payvo-wallet/issues/998

### How to test

An easy way to test with different values on the charts is to hardcode an array of values (otherwise you are going to need to have wallets in different networks with money)

To do that:
1. open the fike `src/domains/dashboard/hooks/use-portfolio-breakdown.ts`
2. Replace the `portfolioItems` assignation with this snippet (see the latest screenshot for a diff example), also feel free to update the percents manually
```php

		const portfolioItems = [
			{
				amount: 373.133_657_93,
				convertedAmount: 302.238_262_923_300_06,
				label: "ARK",
				percent: 50.5,
			},
			{
				amount: 222.133_657_93,
				convertedAmount: 22.238_262_923_300_06,
				label: "BLK",
				percent: 21.5,
			},
			{
				amount: 222.133_657_93,
				convertedAmount: 22.238_262_923_300_06,
				label: "BIND",
				percent: 15.6,
			},
			{
				amount: 222.133_657_93,
				convertedAmount: 22.238_262_923_300_06,
				label: "XQR",
				percent: 12.3,
			},
		];
```

https://user-images.githubusercontent.com/17262776/155387355-12ffb4c8-dc80-4cc3-96c6-8fe10722a2dc.mov

https://user-images.githubusercontent.com/17262776/155387370-fae0ab37-780f-4d7f-962c-9952ca39a667.mov

https://user-images.githubusercontent.com/17262776/155387373-54f5a71b-57ec-4728-9550-48a692ab4680.mov

https://user-images.githubusercontent.com/17262776/155387377-d1cb38d4-6278-4a35-b7f6-5ed6beaf0636.mov

![image](https://user-images.githubusercontent.com/17262776/155388034-edc67dcb-91cf-4f03-9e01-d0f14d237779.png)

## Checklist

-   [x] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [x] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-02-24 01:20 UTC, dated commented
![image](https://user-images.githubusercontent.com/6547002/155438840-97dcb30f-dc70-4744-a4ff-146cc1d16ab6.png)

These Skeletons need to be aligned to the right

2022-02-24 15:56 UTC, alfonsobries commented
@dated ✅

2022-02-24 16:00 UTC, dated approved these changes

2022-02-25 10:17 UTC, samharperpittam requested changes
@alfonsobries - Not sure if it's just me but it appears on breakpoint 768, 640 and 375 the 'More Details' link stops working. Is it possible for you to check that please?

2022-02-25 10:31 UTC, faustbrian commented on src/app/components/Graphs/LineGraph/LineGraph.tsx
> +				text-theme-success-600 text-theme-warning-600 text-theme-info-600 text-theme-danger-400 text-theme-hint-400
You can whitelist those in the config so they don't get removed if they aren't used anywhere else.

2022-02-25 15:52 UTC, alfonsobries commented
@samharperpittam cannot replicate the issue, the button is working for me in all screen sizes

the only issue I have is that the modal looks unaligned. This is happening because other elements in the page are larger than the screen but should be fixed once we implement the responsive version of the rest of the elements.
 
![image](https://user-images.githubusercontent.com/17262776/155745478-48cabe0e-b854-4b35-845d-34c3873d5be1.png)

Can you please try again or give me more details (browser, etc)

2022-02-25 17:22 UTC, alfonsobries commented
@samharperpittam only found an issue with a hidden tooltip container that was interfering with the button, I assume that was your issue, can you please try again?

2022-03-01 12:41 UTC, samharperpittam commented
> 

Yeah that's fixed now. Thanks!

2022-03-01 12:41 UTC, samharperpittam approved these changes

2022-03-01 15:34 UTC, merged