[wip] feat: select account responsive
ArkEcosystem/payvo-wallet pull request #1113
Opened 2022-03-04 19:13 UTC by alfonsobries

## Summary

Closes https://github.com/ArkEcosystem/payvo-wallet/issues/1079

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-03-07 10:35 UTC, samharperpittam requested changes
**640 & 375**

- The network icons are missing the circle around them which is shown within the designs.

**Design**
<img width="346" alt="image" src="https://user-images.githubusercontent.com/44671015/157014871-ac539a4f-b460-437c-9343-3cff1c7d97d9.png">

**Implementation**
<img width="222" alt="image" src="https://user-images.githubusercontent.com/44671015/157014942-73130d92-eeeb-4372-aa07-3917fc96a9c4.png">

2022-03-08 01:02 UTC, alfonsobries commented
@samharperpittam ✅

2022-03-08 12:50 UTC, samharperpittam approved these changes

2022-03-08 15:16 UTC, ItsANameToo approved these changes

2022-03-08 15:16 UTC, merged