[wip] refactor: wallet details implement responsive vote designs
ArkEcosystem/payvo-wallet pull request #1136
Opened 2022-03-08 22:13 UTC by alfonsobries

## Summary

Depends on https://github.com/ArkEcosystem/payvo-wallet/pull/1126
Closes: https://github.com/ArkEcosystem/payvo-wallet/issues/1130

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-03-14 11:38 UTC, samharperpittam requested changes
**Pending Transactions 640**
- When on breakpoint 640 & 375, use compact icons
- Sender doesn't appear to be right aligned
- Delete button should be right aligned
<img width="687" alt="image" src="https://user-images.githubusercontent.com/44671015/158163777-1b5bcf41-e62c-42de-a4a3-243dbb0aaa8b.png">

**Pending 375**
- Content exceeds width 375
- Delete button should be full width with 'Remove' text within the button
<img width="476" alt="image" src="https://user-images.githubusercontent.com/44671015/158163926-8f810c21-a758-4aca-9ee1-b277eb5f9f23.png">

2022-03-14 11:42 UTC, samharperpittam requested changes
Also on this PR it appears the Pending Transaction table has a few issues in Desktop too.
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/44671015/158165159-206a91bd-b8f9-416e-bb9e-c2587ba90349.png">

Interesting Sign button placement :D

2022-03-14 18:22 UTC, alfonsobries commented
@samharperpittam ✅

2022-03-15 11:32 UTC, samharperpittam approved these changes

2022-03-15 12:16 UTC, merged